use_frameworks!

platform :ios, '13.0'

target 'LuckySanboxStorable_Example' do
  pod 'LuckySanboxStorable', :path => '../'

  target 'LuckySanboxStorable_Tests' do
    inherit! :search_paths

    
  end
end
